version: '2'
services:
  picdemo-app:
    image: picdemo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://picdemo-mariadb:3306/picdemo
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  picdemo-mariadb:
    extends:
      file: mariadb.yml
      service: picdemo-mariadb
